Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2018-04, with the labels that each got.

#3247 Revert "Switch IsGrantedAsync(user) and IsGrantedAsync(userId)"
  src/Abp.Zero/Authorization/Users/AbpUserManager.cs
  src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
Labels: bug

#3250 Don't save property history for EntityChange.EntityId
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: enhancement

#3253 fixes #1240: implemented DisableDateTimeNormalizationAttribute
  src/Abp.AspNetCore/AspNetCore/AbpServiceCollectionExtensions.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/ModelBinding/AbpDateTimeModelBinderProvider.cs
  src/Abp.EntityFramework/EntityFramework/Utils/DateTimePropertyInfoHelper.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpEntityMaterializerSource.cs
  src/Abp.NHibernate/NHibernate/Interceptors/AbpNHibernateInterceptor.cs
  src/Abp.Web.Api/WebApi/AbpWebApiModule.cs
  src/Abp.Web.Api/WebApi/Controllers/Dynamic/Binders/AbpApiDateTimeBinder.cs
  src/Abp.Web.Mvc/Web/Mvc/ModelBinding/Binders/AbpMvcDateTimeBinder.cs
  src/Abp/Json/AbpCamelCasePropertyNamesContractResolver.cs
  src/Abp/Json/AbpContractResolver.cs
  src/Abp/Json/JsonExtensions.cs
  src/Abp/Json/JsonSerializationHelper.cs
  src/Abp/Reflection/ReflectionHelper.cs
  src/Abp/Timing/DisableDateTimeNormalization.cs
  test/Abp.AspNetCore.Tests/App/Controllers/SimpleTestController.cs
  test/Abp.AspNetCore.Tests/App/Models/SimpleDateRangeModel.cs
  test/Abp.AspNetCore.Tests/Tests/DateTimeModelBinder_Tests.cs
  test/Abp.EntityFrameworkCore.Tests/Domain/Blog.cs
  test/Abp.EntityFrameworkCore.Tests/Ef/BloggingDbContext.cs
  test/Abp.EntityFrameworkCore.Tests/EntityFrameworkCoreModuleTestBase.cs
  test/Abp.EntityFrameworkCore.Tests/Tests/DateTimeKind_Notmalization_Tests.cs
  test/Abp.EntityFrameworkCore.Tests/Tests/EntityUtcDateTime_Tests.cs
  test/Abp.NHibernate.Tests/AbpNHibernateInterceptor_Tests.cs
  test/Abp.NHibernate.Tests/Entities/Order.cs
  test/Abp.NHibernate.Tests/Entities/OrderDetail.cs
  test/Abp.NHibernate.Tests/Entities/OrderMap.cs
  test/Abp.NHibernate.Tests/NHibernateTestBase.cs
  test/Abp.TestBase.SampleApplication.Tests/EntityFramework/ObjectMaterialize_Tests.cs
  test/Abp.TestBase.SampleApplication.Tests/SampleApplicationTestBase.cs
  test/Abp.TestBase.SampleApplication/Crm/Address.cs
  test/Abp.TestBase.SampleApplication/Crm/Company.cs
  test/Abp.TestBase.SampleApplication/Crm/Hotel.cs
  test/Abp.TestBase.SampleApplication/Crm/Room.cs
  test/Abp.TestBase.SampleApplication/EntityFramework/SampleApplicationDbContext.cs
  test/Abp.Tests/Json/EntityDtoSerialization_Tests.cs
  test/Abp.Tests/Json/JsonExtensions_Tests.cs
  test/Abp.Tests/Json/JsonSerializationHelper_Tests.cs
  test/Abp.Tests/Reflection/ReflectionHelper_Tests.cs
Labels: feature

#3255 fixes #3254: handle tenancyName extraction from url when virtual path is used
  src/Abp.AspNetCore/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs
  src/Abp.Web/Web/MultiTenancy/DomainTenantResolveContributor.cs
  src/Abp/Text/FormattedStringValueExtracter.cs
  test/Abp.AspNetCore.Tests/Tests/MultiTenancy_Tests.cs
Labels: enhancement

#3290 fixes #3289: use zh-Hans instead of zh-CN
  src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-zh-Hans.xml
  src/Abp.Zero.Common/Zero/Localization/Source/AbpZero-zh-Hans.xml
  src/Abp.Zero.Ldap/Ldap/Localization/Source/AbpZero-zh-Hans.xml
  src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-zh-Hans.xml
  src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-zh-Hans.xml
  src/Abp/Localization/Sources/AbpXmlSource/Abp-zh-Hans.xml
  test/Abp.Tests/Localization/Json/JsonAndXmlSourceMixing_Tests.cs
  test/Abp.Tests/Localization/Json/JsonEmbeddedFileLocalizationDictionaryProvider_Tests.cs
  test/Abp.Tests/Localization/Json/JsonSources/Lang-zh-Hans.json
  test/Abp.Tests/Localization/Json/XmlSources/Lang-zh-Hans.xml
  test/Abp.Zero.SampleApp.NHibernateTests/NHibernate/TestDatas/InitialTestLanguagesBuilder.cs
  test/Abp.Zero.SampleApp.Tests/Localization/ApplicationLanguageProvider_Tests.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestLanguagesBuilder.cs
Labels: breaking change
