Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2018-11, with the labels that each got.

#3986 Fix ContainsKey called with null if cookie auth not used
  src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpAutoValidateAntiforgeryTokenAuthorizationFilter.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpValidateAntiforgeryTokenAuthorizationFilter.cs
Labels: bug

#4012 Added code sample
  doc/WebSite/Logging.md
Labels: documentation

#3976 Handle entity history for owned entities
  doc/WebSite/Entity-History.md
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs
  test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
  test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: enhancement
