Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2018-03, with the labels that each got.

#3115 Better support for multiple SignalR hubs
  doc/WebSite/SignalR-AspNetCore-Integration.md
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr.d.ts
Labels: enhancement

#3155 Set FeatureDependencyContext.TenantId before using
  src/Abp.Zero/Authorization/Users/AbpUserManager.cs
  src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
Labels: bug

#3072 Add ability to attach custom method invocation validators through Con…
  src/Abp.AspNetCore/AspNetCore/Mvc/Validation/MvcActionInvocationValidator.cs
  src/Abp.Web.Api/WebApi/Validation/WebApiActionInvocationValidator.cs
  src/Abp.Web.Common/Web/Validation/ActionInvocationValidatorBase.cs
  src/Abp.Web.Mvc/Web/Mvc/Validation/MvcActionInvocationValidator.cs
  src/Abp/AbpKernelModule.cs
  src/Abp/Configuration/Startup/IValidationConfiguration.cs
  src/Abp/Configuration/Startup/ValidationConfiguration.cs
  src/Abp/Runtime/Validation/Interception/CustomValidator.cs
  src/Abp/Runtime/Validation/Interception/DataAnnotationsValidator.cs
  src/Abp/Runtime/Validation/Interception/IMethodParameterValidator.cs
  src/Abp/Runtime/Validation/Interception/MethodInvocationValidator.cs
  src/Abp/Runtime/Validation/Interception/ValidatableObjectValidator.cs
  test/Abp.AspNetCore.Tests/App/Controllers/ValidationTestController.cs
  test/Abp.AspNetCore.Tests/Tests/Validation_Tests.cs
Labels: feature

#3229 Standardize capitalization, correct spellings in documents
  .github/ISSUE_TEMPLATE
  README.md
  doc/WebSite/About.md
  doc/WebSite/Articles-Tutorials.md
  doc/WebSite/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular5.md
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html
  doc/WebSite/Articles/Developing-a-Multi-Tenant-SaaS-Application-with-ASP.NET-MVC-EntityFramework-AngularJs/index.html
  doc/WebSite/Articles/Introduction-With-AspNet-Core-And-Entity-Framework-Core-Part-1/index.html
  doc/WebSite/Articles/Introduction-With-AspNet-Core-And-Entity-Framework-Core-Part-2/index.html
  doc/WebSite/Articles/Introduction-With-AspNet-MVC-Web-API-EntityFramework-and-AngularJs/index.html
  doc/WebSite/Articles/Running-in-Docker-Containers-and-Building-a-Web-Farm-Load-Balancer-Scenario/index.html
  doc/WebSite/Articles/Unit-Testing-with-Entity-Framework,-xUnit-Effort/index.html
  doc/WebSite/Articles/Using-Stored-Procedures,-User-Defined-Functions-and-Views/index.html
  doc/WebSite/Change-Logs.md
  doc/WebSite/Document-Index.md
  doc/WebSite/Documents.md
  doc/WebSite/Dynamic-Web-API.md
  doc/WebSite/Introduction.md
  doc/WebSite/Javascript-API/Message.md
  doc/WebSite/Javascript-API/Notification.md
  doc/WebSite/SignalR-AspNetCore-Integration.md
  doc/WebSite/XSRF-CSRF-Protection.md
  doc/WebSite/Zero/Overall.md
  doc/WebSite/Zero/Startup-Template-Angular.md
  doc/WebSite/Zero/Startup-Template-Core.md
  doc/WebSite/Zero/Startup-Template.md
  src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/AbpServiceProxiesController.cs
  src/Abp.Web.Common/Web/Api/ProxyScripting/Generators/JQuery/JQueryProxyScriptGenerator.cs
  src/Abp.Web.Common/Web/Authorization/IAuthorizationScriptManager.cs
  src/Abp.Web.Common/Web/Features/IFeaturesScriptManager.cs
  src/Abp.Web.Common/Web/Localization/ILocalizationScriptManager.cs
  src/Abp.Web.Common/Web/Settings/ISettingScriptManager.cs
  src/Abp.Web.Common/Web/Timing/ITimingScriptManager.cs
  src/Abp.Web.Mvc/Web/Mvc/Resources/WebResourceHelper.cs
  src/Abp.Web.Mvc/Web/Mvc/Security/AntiForgery/AbpMvcAntiForgeryTokenManager.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/wwwroot/js/site.js
Labels: documentation

#3239 Set TenantId for IMayHaveTenant entities (Entity History)
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
Labels: bug
