Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2018-09, with the labels that each got.

#3825 AbpProfileService.IsActiveAsync doesn't check if the user is Active
  src/Abp.ZeroCore.IdentityServer4/IdentityServer4/AbpProfileService.cs
Labels: enhancement

#3828 Child feature remove
  src/Abp/Application/Features/Feature.cs
  test/Abp.TestBase.SampleApplication.Tests/Features/FeatureSystem_Tests.cs
  test/Abp.TestBase.SampleApplication/ContacLists/SampleFeatureProvider.cs
Labels: enhancement

#3852 Remove outdated notice about IdentityServer4.AccessTokenValidation package
  doc/WebSite/Zero/Identity-Server.md
Labels: documentation

#3867 Fix AuditedAttribute on property creating history for every property
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: bug

#3864 Bugfix: Add using singleton Castle ProxyGenerator to avoid memoryleak in unit tests
  src/Abp/Dependency/IocManager.cs
Labels: enhancement

#3871 Fix model binding for OData Patch, Post, Put
  src/Abp.AspNetCore.OData/AspNetCore/OData/Configuration/AbpAspNetCoreODataModuleConfiguration.cs
  src/Abp.AspNetCore.OData/AspNetCore/OData/Controllers/AbpODataEntityController.cs
Labels: bug

#3874 Remove outdated notice about EF Core Query Filters
  doc/WebSite/About.md
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular5.md
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html
  doc/WebSite/AspNet-Core.md
  doc/WebSite/Data-Filters.md
  doc/WebSite/Localization.md
  doc/WebSite/Logging.md
  doc/WebSite/Multi-Tenancy.md
  doc/WebSite/Startup-Configuration.md
  doc/WebSite/XSRF-CSRF-Protection.md
  doc/WebSite/Zero/Identity-Server.md
  src/Abp/Modules/AbpModule.cs
  src/Abp/Runtime/Validation/ICustomValidate.cs
  test/Abp.TestBase.SampleApplication.Tests/ContactLists/ContactList_MultiTenancy_Tests.cs
  test/Abp.TestBase.SampleApplication.Tests/ContactLists/Messages_MultiTenancy_Tests.cs
Labels: documentation

#3888 Refactor singleton instance
  src/Abp.Zero.Common/Authorization/Roles/PermissionEqualityComparer.cs
  src/Abp/Application/Features/NullFeatureValueStore.cs
  src/Abp/Events/Bus/NullEventBus.cs
  src/Abp/Localization/NullLocalizationManager.cs
  src/Abp/Localization/Sources/NullLocalizationSource.cs
  src/Abp/Notifications/NullRealTimeNotifier.cs
  src/Abp/ObjectMapping/NullObjectMapper.cs
  src/Abp/Runtime/Security/SimpleStringCipher_NetStandard.cs
Labels: enhancement
