Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-04, with the labels that each got.

#4358 Entity History Support for EF6
  doc/WebSite/Entity-History.md
  src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs
  src/Abp.Zero.EntityFramework/EntityHistory/IEntityHistoryHelper.cs
  src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs
  src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbModelBuilderExtensions.cs
  test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestBlogBuilder.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestDataBuilder.cs
  test/Abp.Zero.SampleApp/EntityHistory/Blog.cs
  test/Abp.Zero.SampleApp/EntityHistory/Comment.cs
  test/Abp.Zero.SampleApp/EntityHistory/Post.cs
Labels: feature

#4471 Add documentation for multiple notification notifiers
  doc/WebSite/Notification-System.md
  doc/WebSite/SignalR-AspNetCore-Integration.md
Labels: documentation

#4477 Fix user role permission cache
  src/Abp.Zero.Common/Authorization/Roles/AbpRolePermissionCacheItemInvalidator.cs
  src/Abp.Zero.Common/Authorization/Users/AbpUserPermissionCacheItemInvalidator.cs
  test/Abp.ZeroCore.Tests/Zero/Users/UserManager_AddToRole_Tests.cs
  test/Abp.ZeroCore.Tests/Zero/Users/UserManager_Permission_Tests.cs
Labels: problem

#4450 Add AbpExceptionPageFilter and AbpResultPageFilter for Razor Page.
  src/Abp.AspNetCore/AspNetCore/Mvc/AbpMvcOptionsExtensions.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditPageFilter.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionPageFilter.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultPageFilter.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpActionResultWrapperFactory.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpEmptyActionResultWrapper.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpJsonActionResultWrapper.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpObjectActionResultWrapper.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/IAbpActionResultWrapper.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/IAbpActionResultWrapperFactory.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/NullAbpActionResultWrapper.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Uow/AbpUowPageFilter.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorExceptionPageFilterTests.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorResultPageFilterTests.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ExceptionFilterPageDemo.cshtml
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ExceptionFilterPageDemo.cshtml.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ResultFilterPageDemo.cshtml
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ResultFilterPageDemo.cshtml.cs
Labels: enhancement

#4489 fix #4488 The filter is no longer executed when the HandlerMethod is null.
  src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditPageFilter.cs
  src/Abp.AspNetCore/AspNetCore/Mvc/Uow/AbpUowPageFilter.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorAuditPageFilterTests.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorUowPageFilterTests.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo4.cshtml
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo4.cshtml.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo3.cshtml
  test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo3.cshtml.cs
Labels: enhancement
