Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-02, with the labels that each got.

#4241 Fix incorrect multi-tenancy side for AbpZeroTenantDbContext
  src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroTenantDbContext.cs
  src/Abp.Zero.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroTenantDbContext.cs
  src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroTenantDbContext.cs
  src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroTenantDbContext.cs
Labels: breaking change

#4198 AuditInfo add record returnvalue
  src/Abp/Auditing/AuditInfo.cs
  src/Abp/Auditing/AuditingConfiguration.cs
  src/Abp/Auditing/AuditingInterceptor.cs
  src/Abp/Auditing/IAuditingConfiguration.cs
  src/Abp/Threading/InternalAsyncHelper.cs
  test/Abp.TestBase.SampleApplication.Tests/Auditing/SimpleAuditing_Test.cs
Labels: feature

#4314 Auto-connect SignalR only if not already configured
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.min.js
Labels: enhancement
