Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-07, with the labels that each got.

#4679 fix #4677 AddUserNotificationCountAsync method to add filter parameters.
  src/Abp.Zero.Common/Notifications/NotificationStore.cs
  src/Abp/Notifications/INotificationStore.cs
  src/Abp/Notifications/IUserNotificationManager.cs
  src/Abp/Notifications/NullNotificationStore.cs
  src/Abp/Notifications/UserNotificationManager.cs
Labels: enhancement

#4702 Refactor event trigger async background job
  src/Abp/AbpKernelModule.cs
  src/Abp/BackgroundJobs/BackgroundJobManagerEventTriggerExtensions.cs
  src/Abp/BackgroundJobs/EventTriggerAsyncBackgroundJob.cs
Labels: refactoring

#4700 OrganizationUnitRole change event handler is updated.
  src/Abp.Zero.Common/Authorization/Users/AbpUserPermissionCacheItemInvalidator.cs
Labels: problem

#4479 Alert System with Toastr option
  doc/WebSite/UI-Alerts.md
  src/Abp.Web.Common/Web/Mvc/Alerts/AlertDisplayType.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/AlertList.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/AlertMessage.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/AlertMessageRendererManager.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/IAlertMessageRenderer.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/IAlertMessageRendererManager.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/PageAlertMessageRenderer.cs
  src/Abp.Web.Common/Web/Mvc/Alerts/ToastrAlertMessageRenderer.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Controllers/AlertsTestController.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo/Views/AlertsTest/Index.cshtml
  test/aspnet-core-demo/AbpAspNetCoreDemo/wwwroot/lib/toastr/toastr.css
  test/aspnet-core-demo/AbpAspNetCoreDemo/wwwroot/lib/toastr/toastr.min.js
Labels: enhancement

#4747 fix async background job ioc registration
  src/Abp/AbpKernelModule.cs
Labels: problem
