Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-03, with the labels that each got.

#4330 Support multiple notification notifiers
  src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/AbpAspNetCoreSignalRModule.cs
  src/Abp.Web.SignalR/Web/SignalR/AbpWebSignalRModule.cs
  src/Abp/Notifications/DefaultNotificationDistributer.cs
  src/Abp/Notifications/INotificationConfiguration.cs
  src/Abp/Notifications/NotificationConfiguration.cs
  src/Abp/Notifications/NullRealTimeNotifier.cs
  test/Abp.ZeroCore.Tests/Zero/Notifications/IRealTimeNotifier2.cs
  test/Abp.ZeroCore.Tests/Zero/Notifications/RealTimeNotifier_Tests.cs
Labels: feature

#4341 Organization unit operations
  src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs
  src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
  test/Abp.Zero.SampleApp.Tests/Roles/OrganizationUnitRole_Tests.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialOrganizationUnitRolesBuilder.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialRolesBuilder.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestDataBuilder.cs
  test/Abp.Zero.SampleApp/Roles/RoleManager.cs
  test/Abp.ZeroCore.SampleApp/Core/_Service_Overrides.cs
Labels: breaking change, enhancement

#4372 Move app.MapSignalR to end of Configuration method
  doc/WebSite/SignalR-Integration.md
Labels: documentation

#4390 Added OnlineClientStore for OnlineClientManager
  src/Abp/AbpKernelModule.cs
  src/Abp/Data/ConditionalValue.cs
  src/Abp/RealTime/IOnlineClientManager.cs
  src/Abp/RealTime/IOnlineClientStore.cs
  src/Abp/RealTime/InMemoryOnlineClientStore.cs
  src/Abp/RealTime/OnlineClientManager.cs
  test/Abp.Tests/RealTime/InMemoryOnlineClientManager_Tests.cs
  test/Abp.Tests/RealTime/InMemoryOnlineClientStore_Tests.cs
Labels: feature
