Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-10, with the labels that each got.

#4909 Refactoring the abp.message function.
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.js
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.min.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.sweet-alert.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.sweet-alert.min.js
Labels: breaking change

#4843 Entity History EF6 flow
  src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs
  src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbEntityEntryExtensions.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestBlogBuilder.cs
Labels: enhancement

#4870 Entity History EfCore flow
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/Extensions/EntityEntryExtensions.cs
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/Extensions/PropertyEntryExtensions.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: enhancement

#4516 Entity History handle invalid entity with audited property
  test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.Zero.SampleApp/EntityHistory/Category.cs
  test/Abp.Zero.SampleApp/EntityHistory/Post.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Category.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Post.cs
  test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: problem

#4901 Update entity history test
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: refactoring

#4929 remove overrided equality methods
  src/Abp/Domain/Entities/Entity.cs
  src/Abp/Domain/Values/ValueObject.cs
  test/Abp.Tests/Domain/Entities/Test_Entities.cs
  test/Abp.Tests/Domain/Values/ValueObject_Simple_Tests.cs
Labels: breaking change

#4968 Remove non-sweetalert parameter(isHtml)
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.sweet-alert.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.sweet-alert.min.js
Labels: enhancement
