Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-08, with the labels that each got.

#4777 order of culture provider has been changed
  doc/WebSite/Localization.md
  src/Abp.AspNetCore/AspNetCore/AbpApplicationBuilderExtensions.cs
Labels: breaking change

#4770 Refactor AbpRepositoryBase async operations
  src/Abp/Domain/Repositories/AbpRepositoryBase.cs
Labels: enhancement

#4813 Entity History EF6 Complex Type property null value
  src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbComplexPropertyEntryExtensions.cs
  src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbPropertyEntryExtensions.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
Labels: bug

#4823 Prevent null being saved into user's DefaultLanguage
  src/Abp.AspNetCore/AspNetCore/Localization/AbpDefaultRequestCultureProvider.cs
  src/Abp.AspNetCore/AspNetCore/Localization/AbpLocalizationHeaderRequestCultureProvider.cs
  src/Abp.AspNetCore/AspNetCore/Localization/AbpUserRequestCultureProvider.cs
Labels: enhancement

#4807 Changes security stamp when password change via using ChangePasswordAsync function
  src/Abp.Zero/Authorization/Users/AbpUserManager.cs
  src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
  test/Abp.Zero.SampleApp.Tests/Users/UserAppService_Tests.cs
  test/Abp.Zero.SampleApp.Tests/Users/UserManager_SecurityStamp_Tests.cs
Labels: breaking change

#4824 fix localization dictionary providers
  src/Abp/Localization/Dictionaries/Json/JsonEmbeddedFileLocalizationDictionaryProvider.cs
  src/Abp/Localization/Dictionaries/Json/JsonFileLocalizationDictionaryProvider.cs
  src/Abp/Localization/Dictionaries/LocalizationDictionaryProviderBase.cs
  src/Abp/Localization/Dictionaries/Xml/XmlEmbeddedFileLocalizationDictionaryProvider.cs
  src/Abp/Localization/Dictionaries/Xml/XmlFileLocalizationDictionaryProvider.cs
Labels: breaking change, enhancement

#4722 Generic CacheManagerBase
  doc/WebSite/Caching.md
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheManager.cs
  src/Abp/Runtime/Caching/CacheManagerBase.cs
  src/Abp/Runtime/Caching/Configuration/CacheConfigurator.cs
  src/Abp/Runtime/Caching/Configuration/CachingConfiguration.cs
  src/Abp/Runtime/Caching/Configuration/ICacheConfigurator.cs
  src/Abp/Runtime/Caching/Configuration/ICachingConfiguration.cs
  src/Abp/Runtime/Caching/ICache.cs
  src/Abp/Runtime/Caching/ICacheManager.cs
  src/Abp/Runtime/Caching/ICacheOptions.cs
  src/Abp/Runtime/Caching/ITypedCache.cs
  src/Abp/Runtime/Caching/Memory/AbpMemoryCacheManager.cs
Labels: breaking change, refactoring
