Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2019-12, with the labels that each got.

#5070 Application will not use disabled languages by default
  src/Abp.AspNetCore/AspNetCore/AbpApplicationBuilderExtensions.cs
  src/Abp.FluentValidation/FluentValidation/AbpFluentValidationLanguageManager.cs
  src/Abp.Web.Common/Web/Configuration/AbpUserConfigurationBuilder.cs
  src/Abp.Web.Common/Web/Localization/LocalizationScriptManager.cs
  src/Abp.Zero.Common/Localization/ApplicationLanguageManager.cs
  src/Abp.Zero.Common/Localization/ApplicationLanguageProvider.cs
  src/Abp.Zero.Common/Localization/IApplicationLanguageManager.cs
  src/Abp.Zero.Common/Localization/MultiTenantLocalizationDictionaryProvider.cs
  src/Abp/Localization/DefaultLanguageProvider.cs
  src/Abp/Localization/ILanguageManager.cs
  src/Abp/Localization/ILanguageProvider.cs
  src/Abp/Localization/LanguageManager.cs
  test/Abp.Tests/Localization/DefaultLanguageProvider_Test.cs
  test/Abp.Zero.SampleApp.Tests/Localization/ApplicationLanguageManager_Tests.cs
Labels: breaking change

#5027 Remove limitation on AppSettings table value column
  src/Abp.Zero.Common/Configuration/Setting.cs
Labels: enhancement

#5139 Determine if the IP contains ":"
  src/Abp.Web/Auditing/WebClientInfoProvider.cs
Labels: problem

#5137 Enhance EFPlus' extension methods to support BatchDelete & BatchUpdate.
  src/Abp.EntityFrameworkCore.EFPlus/Abp.EntityFrameworkCore.EFPlus.csproj
  src/Abp.EntityFrameworkCore.EFPlus/EntityFrameworkCore/EFPlus/AbpEntityFrameworkCoreEFPlusExtensions.cs
Labels: feature

#5136 Enhance EFPlus' extension methods to support BatchDelete & BatchUpdate.
  src/Abp.EntityFrameworkCore.EFPlus/Abp.EntityFrameworkCore.EFPlus.csproj
  src/Abp.EntityFrameworkCore.EFPlus/EntityFrameworkCore/EFPlus/AbpEntityFrameworkCoreEFPlusExtensions.cs
Labels: feature

#5166 Added RoleDisplayName property to StaticRoleDefinition class.
  src/Abp.Zero.Common/Zero/Configuration/StaticRoleDefinition.cs
  src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs
  src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
Labels: enhancement

#5167 Added RoleDisplayName property to StaticRoleDefinition class.
  src/Abp.Zero.Common/Zero/Configuration/StaticRoleDefinition.cs
  src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs
  src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
Labels: enhancement
