Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2020-04, with the labels that each got.

#5480 Make PredicateBuilder public
  src/Abp/Linq/Expressions/PredicateBuilder.cs
Labels: enhancement

#5478 Enhanced setCookieValue method.
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.js
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.min.js
Labels: enhancement

#5441 Implementation of Object Comparators
  src/Abp/ObjectComparators/BooleanComparators/BooleanCompareTypes.cs
  src/Abp/ObjectComparators/BooleanComparators/BooleanObjectComparator.cs
  src/Abp/ObjectComparators/DateTimeComparators/DateTimeCompareTypes.cs
  src/Abp/ObjectComparators/DateTimeComparators/DateTimeObjectComparator.cs
  src/Abp/ObjectComparators/IObjectComparator.cs
  src/Abp/ObjectComparators/IObjectComparatorManager.cs
  src/Abp/ObjectComparators/IntComparators/IntCompareTypes.cs
  src/Abp/ObjectComparators/IntComparators/IntObjectComparator.cs
  src/Abp/ObjectComparators/LongComparators/LongCompareTypes.cs
  src/Abp/ObjectComparators/LongComparators/LongObjectComparator.cs
  src/Abp/ObjectComparators/ObjectComparatorBase.cs
  src/Abp/ObjectComparators/ObjectComparatorCondition.cs
  src/Abp/ObjectComparators/ObjectComparatorExtensions.cs
  src/Abp/ObjectComparators/ObjectComparatorManager.cs
  src/Abp/ObjectComparators/StringComparators/StringCompareTypes.cs
  src/Abp/ObjectComparators/StringComparators/StringObjectComparator.cs
  test/Abp.Tests/Abp.Tests.csproj
  test/Abp.Tests/ObjectComparators/BooleanComparators_Tests.cs
  test/Abp.Tests/ObjectComparators/DateTimeObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/IntObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/LongObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/NullableBooleanComparators_Tests.cs
  test/Abp.Tests/ObjectComparators/NullableDateTimeObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/NullableIntObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/NullableLongObjectComparator_Tests.cs
  test/Abp.Tests/ObjectComparators/ObjectComparatorManager_Tests.cs
  test/Abp.Tests/ObjectComparators/ObjectComparatorTestBase.cs
  test/Abp.Tests/ObjectComparators/StringObjectComparator_Tests.cs
Labels: feature

#5501 Adds send exact same data option to Webhook System
  src/Abp/Webhooks/DefaultWebhookPublisher.cs
  src/Abp/Webhooks/DefaultWebhookSender.cs
  src/Abp/Webhooks/IWebhookPublisher.cs
  src/Abp/Webhooks/WebhookSenderArgs.cs
  test/Abp.Zero.SampleApp.Tests/Webhooks/DefaultWebhookSender_Tests.cs
Labels: enhancement

#5507 Add document about nuke build.
  build/README.md
  doc/img/nuke-build-command-prompt.png
Labels: documentation
