Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2020-06, with the labels that each got.

#5334 AbpCacheBase introduces TryGetValue
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs
  src/Abp/Data/ConditionalValue.cs
  src/Abp/Runtime/Caching/AbpCacheBase.cs
  src/Abp/Runtime/Caching/IAbpCache.cs
  src/Abp/Runtime/Caching/Memory/AbpMemoryCache.cs
  src/Abp/Runtime/Caching/TypedCacheWrapper.cs
Labels: breaking-change

#5644 Filter undefined settings in the ConvertSettingInfosToDictionary method.
  src/Abp/Configuration/SettingManager.cs
  test/Abp.Tests/Configuration/SettingManager_Tests.cs
Labels: enhancement

#5643 Filter undefined settings in the ConvertSettingInfosToDictionary method.
  src/Abp/Configuration/SettingManager.cs
  test/Abp.Tests/Configuration/SettingManager_Tests.cs
Labels: enhancement

#5655 Refactor the HardDelete function to ensure that there is a unit of work in the current context.
  src/Abp/Domain/Repositories/RepositoryExtensions.cs
  test/Abp.Zero.SampleApp.Tests/Repository/Repository_Hard_Delete_Test.cs
  test/Abp.ZeroCore.Tests/Zero/Repository/Repository_Hard_Delete_Test.cs
Labels: enhancement

#5656 Refactor the HardDelete function to ensure that there is a unit of work in the current context.
  src/Abp/Domain/Repositories/RepositoryExtensions.cs
  test/Abp.Zero.SampleApp.Tests/Repository/Repository_Hard_Delete_Test.cs
  test/Abp.ZeroCore.Tests/Zero/Repository/Repository_Hard_Delete_Test.cs
Labels: enhancement

#5670 Update MultiTenantLocalizationDictionaryProvider.cs
  src/Abp.Zero.Common/Localization/MultiTenantLocalizationDictionaryProvider.cs
Labels: problem

#5686 Optimize the cache performance of the GetUserSettingConfig method.
  src/Abp.Web.Common/Web/Configuration/AbpUserConfigurationBuilder.cs
Labels: effort-0.5
