Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2020-02, with the labels that each got.

#5207 Modify Async interception logic
  src/Abp.Web.Api/WebApi/Controllers/Dynamic/Interceptors/AbpDynamicApiControllerInterceptor.cs
  src/Abp/Abp.csproj
  src/Abp/AbpKernelModule.cs
  src/Abp/Auditing/AuditingInterceptor.cs
  src/Abp/Auditing/AuditingInterceptorRegistrar.cs
  src/Abp/Authorization/AuthorizationInterceptor.cs
  src/Abp/Authorization/AuthorizationInterceptorRegistrar.cs
  src/Abp/Dependency/AbpAsyncDeterminationInterceptor.cs
  src/Abp/Dependency/AbpInterceptorBase.cs
  src/Abp/Domain/Uow/UnitOfWorkInterceptor.cs
  src/Abp/Domain/Uow/UnitOfWorkRegistrar.cs
  src/Abp/EntityHistory/EntityHistoryInterceptor.cs
  src/Abp/EntityHistory/EntityHistoryInterceptorRegistrar.cs
  src/Abp/Runtime/Validation/Interception/ValidationInterceptor.cs
  src/Abp/Runtime/Validation/Interception/ValidationInterceptorRegistrar.cs
  test/Abp.TestBase.SampleApplication.Tests/Auditing/SimpleAuditing_Test.cs
  test/Abp.Tests/Authorization/AuthorizationInterceptor_Tests.cs
  test/Abp.Zero.SampleApp.Tests/SampleAppTestModule.cs
Labels: enhancement

#5181 Generic CacheBase interface and implementation
  src/Abp/Runtime/Caching/AbpCacheBase.cs
  src/Abp/Runtime/Caching/CacheBase.cs
  src/Abp/Runtime/Caching/IAbpCache.cs
  src/Abp/Runtime/Caching/ICache.cs
  src/Abp/Runtime/Caching/ITypedCache.cs
Labels: refactoring

#5151 Entity History will not always create history record for shadow property
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.Zero.SampleApp/EntityHistory/Country.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Country.cs
  test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: bug

#5197 Remove sync methods usage of Async queryable executer
  src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs
  src/Abp.Zero/Authorization/Users/AbpUserStore.cs
  src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs
  src/Abp/Linq/IAsyncQueryableExecuter.cs
Labels: refactoring

#5241 Fix Entity History Retrieve the correct owner
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Advertisement.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs
  test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
  test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: bug

#5192 Update Redis serializer Serialize() return type
  src/Abp.RedisCache.ProtoBuf/Runtime/Caching/Redis/ProtoBufRedisCacheSerializer.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/DefaultRedisCacheSerializer.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/IRedisCacheSerializer.cs
  test/Abp.RedisCache.Tests/DefaultRedisCacheSerializer_Tests.cs
  test/Abp.RedisCache.Tests/RedisCacheManager_Test.cs
Labels: breaking change, enhancement

#5284 adds ability to change abp.signal reconnect time increase method.
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
  src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.min.js
Labels: enhancement

#5287 Update SignalR-Integration.md
  doc/WebSite/SignalR-AspNetCore-Integration.md
  doc/WebSite/SignalR-Integration.md
Labels: enhancement

#5111 ICancellationTokenProvider implementation. Fixes #5102
  src/Abp.AspNetCore/AspNetCore/Threading/HttpContextCancellationTokenProvider.cs
  src/Abp.EntityFramework/EntityFramework/Repositories/EfRepositoryBaseOfTEntityAndTPrimaryKey.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/Repositories/EfCoreRepositoryBaseOfTEntityAndTPrimaryKey.cs
  src/Abp.NHibernate/NHibernate/Repositories/NhRepositoryBaseOfTEntityAndTPrimaryKey.cs
  src/Abp.Web.Mvc/Web/Mvc/Threading/HttpContextCancellationTokenProvider.cs
  src/Abp/Domain/Repositories/AbpRepositoryBase.cs
  src/Abp/Domain/Repositories/IRepositoryOfTEntityAndTPrimaryKey.cs
  src/Abp/Threading/ICancellationTokenProvider.cs
  src/Abp/Threading/NullCancellationTokenProvider.cs
Labels: feature

#5289 add ipv6 support to web client info provider
  src/Abp.Web/Auditing/IPEndPointHelper.cs
  src/Abp.Web/Auditing/WebClientInfoProvider.cs
  test/Abp.Web.Tests/Auditing/Client_Info_Provider_Tests.cs
  test/Abp.Web.Tests/EntityHistory/EntityHistory_Reason_Tests.cs
Labels: enhancement

#5201 Remove sync methods usage of Async queryable executer For 4.x
  src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs
  src/Abp.Zero/Authorization/Users/AbpUserStore.cs
  src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs
  src/Abp/Linq/IAsyncQueryableExecuter.cs
Labels: refactoring

#5242 4.x Fix Entity History Retrieve the correct owner
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Advertisement.cs
  test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs
  test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
  test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: bug
