Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2020-03, with the labels that each got.

#5331 Add ASP.NET Core Generic Host support
  src/Abp.AspNetCore/AspNetCore/AbpServiceCollectionExtensions.cs
  src/Abp.AspNetCore/AspNetCore/Dependency/AbpCastleWindsorHostBuilderExtensions.cs
Labels: enhancement

#5350 Improve GetLastChild of OrganizationUnitManager
  src/Abp.Zero.Common/Organizations/OrganizationUnitManager.cs
Labels: enhancement

#5277 AbpCacheBase: Use the value generated by the factory method to return items.
  src/Abp/Runtime/Caching/AbpCacheBase.cs
Labels: bug

#5362 Dynamic Parameter Module
  doc/WebSite/Dynamic-Parameter-System.md
  src/Abp.Zero.Common/DynamicEntityParameters/DynamicParameterStore.cs
  src/Abp.Zero.Common/DynamicEntityParameters/DynamicParameterValueStore.cs
  src/Abp.Zero.Common/DynamicEntityParameters/EntityDynamicParameterStore.cs
  src/Abp.Zero.Common/DynamicEntityParameters/EntityDynamicParameterValueStore.cs
  src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs
  src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbModelBuilderExtensions.cs
  src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs
  src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroDbModelBuilderExtensions.cs
  src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroCommonDbContext.cs
  src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroDbModelBuilderExtensions.cs
  src/Abp/AbpKernelModule.cs
  src/Abp/Configuration/Startup/AbpStartupConfiguration.cs
  src/Abp/Configuration/Startup/IAbpStartupConfiguration.cs
  src/Abp/Dependency/Installers/AbpCoreInstaller.cs
  src/Abp/DynamicEntityParameters/DynamicEntityParameterConfiguration.cs
  src/Abp/DynamicEntityParameters/DynamicEntityParameterDefinitionContext.cs
  src/Abp/DynamicEntityParameters/DynamicEntityParameterDefinitionManager.cs
  src/Abp/DynamicEntityParameters/DynamicEntityParameterDefinitionProvider.cs
  src/Abp/DynamicEntityParameters/DynamicParameter.cs
  src/Abp/DynamicEntityParameters/DynamicParameterManager.cs
  src/Abp/DynamicEntityParameters/DynamicParameterPermissionChecker.cs
  src/Abp/DynamicEntityParameters/DynamicParameterValue.cs
  src/Abp/DynamicEntityParameters/DynamicParameterValueManager.cs
  src/Abp/DynamicEntityParameters/EntityDynamicParameter.cs
  src/Abp/DynamicEntityParameters/EntityDynamicParameterManager.cs
  src/Abp/DynamicEntityParameters/EntityDynamicParameterValue.cs
  src/Abp/DynamicEntityParameters/EntityDynamicParameterValueManager.cs
  src/Abp/DynamicEntityParameters/Extensions/EntityDynamicParameterManagerExtensions.cs
  src/Abp/DynamicEntityParameters/Extensions/EntityDynamicParameterValueManagerExtensions.cs
  src/Abp/DynamicEntityParameters/IDynamicEntityParameterConfiguration.cs
  src/Abp/DynamicEntityParameters/IDynamicEntityParameterDefinitionContext.cs
  src/Abp/DynamicEntityParameters/IDynamicEntityParameterDefinitionManager.cs
  src/Abp/DynamicEntityParameters/IDynamicParameterManager.cs
  src/Abp/DynamicEntityParameters/IDynamicParameterPermissionChecker.cs
  src/Abp/DynamicEntityParameters/IDynamicParameterStore.cs
  src/Abp/DynamicEntityParameters/IDynamicParameterValueManager.cs
  src/Abp/DynamicEntityParameters/IDynamicParameterValueStore.cs
  src/Abp/DynamicEntityParameters/IEntityDynamicParameterManager.cs
  src/Abp/DynamicEntityParameters/IEntityDynamicParameterStore.cs
  src/Abp/DynamicEntityParameters/IEntityDynamicParameterValueManager.cs
  src/Abp/DynamicEntityParameters/IEntityDynamicParameterValueStore.cs
  src/Abp/DynamicEntityParameters/NullDynamicEntityParameterDefinitionManager.cs
  src/Abp/DynamicEntityParameters/NullDynamicParameterStore.cs
  src/Abp/DynamicEntityParameters/NullDynamicParameterValueStore.cs
  src/Abp/DynamicEntityParameters/NullEntityDynamicParameterStore.cs
  src/Abp/DynamicEntityParameters/NullEntityDynamicParameterValueStore.cs
  src/Abp/UI/Inputs/InputTypeBase.cs
  test/Abp.Zero.SampleApp.Tests/DynamicEntityParameters/DynamicEntityParametersTestBase.cs
  test/Abp.Zero.SampleApp.Tests/DynamicEntityParameters/DynamicParameterManager_Tests.cs
  test/Abp.Zero.SampleApp.Tests/DynamicEntityParameters/DynamicParameterValueManager_Tests.cs
  test/Abp.Zero.SampleApp.Tests/DynamicEntityParameters/EntityDynamicParameterManager_Tests.cs
  test/Abp.Zero.SampleApp.Tests/DynamicEntityParameters/EntityDynamicParameterValueManager_Tests.cs
Labels: feature

#5394 Move cache type casting from cache extensions into TypedCacheWrapper
  src/Abp/Runtime/Caching/CacheExtensions.cs
  src/Abp/Runtime/Caching/CacheManagerBase.cs
  src/Abp/Runtime/Caching/TypedCacheWrapper.cs
  test/Abp.Tests/Runtime/Caching/Memory/MemoryCacheManager_Tests.cs
Labels: enhancement

#5412 Add Initialize method for the AbpDbContext(EF 3.x+)
  src/Abp.EntityFramework.Common/AbpEfCoreDbContextInitializationContext.cs
  src/Abp.EntityFramework.Common/IShouldInitializeDcontext.cs
  src/Abp.EntityFramework/EntityFramework/AbpDbContext.cs
  src/Abp.EntityFramework/EntityFramework/Uow/EfUnitOfWork.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/Uow/EfCoreUnitOfWork.cs
Labels: enhancement

#5409 HttpContextCancellationTokenProvider into Abp.Web namespace
  src/Abp.Web/Threading/HttpContextCancellationTokenProvider.cs
Labels: breaking-change

#5406 Mvc cancellation token provider http exception
  src/Abp.Web/Threading/HttpContextCancellationTokenProvider.cs
  src/Abp/Threading/CancellationTokenProviderBase.cs
Labels: enhancement

#5416 Update AdminLTE images. Add libman info
  doc/WebSite/Zero/Startup-Template-Core.md
  doc/WebSite/images/module-zero-core-template-ui-home-2.png
  doc/WebSite/images/module-zero-core-template-ui-login-2.png
Labels: documentation, enhancement

#5450 Await ToListAsync in GetAllSendAttemptsByWebhookEventIdAsync
  src/Abp.Zero.Common/Webhooks/WebhookSendAttemptStore.cs
  test/Abp.Zero.SampleApp.Tests/Webhooks/WebhookSendAttemptStore_Tests.cs
  test/Abp.Zero.SampleApp/Linq/FakeAsyncQueryableExecuter.cs
Labels: bug
