Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2020-01, with the labels that each got.

#5179 extend IAsyncQueryableExecuter with AnyAsync
  src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs
  src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs
  src/Abp/Linq/IAsyncQueryableExecuter.cs
  src/Abp/Linq/NullAsyncQueryableExecuter.cs
Labels: enhancement

#5193 Add TypeScript declarations for refresh token
  src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
Labels: enhancement

#5187 use current tenant Id in PermissionManager GetAllPermission
  src/Abp/Authorization/PermissionManager.cs
  test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
Labels: bug

#5186 use current tenant Id in PermissionManager.cs/GetAllPermission
  src/Abp/Authorization/PermissionManager.cs
  test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
Labels: bug

#5168 Use TimeSpan for user token expiration frequency
  src/Abp.ZeroCore/Authorization/Users/UserTokenExpirationWorker.cs
  src/Abp/BackgroundJobs/BackgroundJobConfiguration.cs
  src/Abp/BackgroundJobs/IBackgroundJobConfiguration.cs
Labels: refactoring
