Repository aspnetboilerplate/aspnetboilerplate, pull requests merged in 2024-02, with the labels that each got.

#6874 Update screenshots and sample codes
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-create-db.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-create-template.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-dashboard.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-event-detail.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-events.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-host-dashboard.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-localization-resources.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-login-page.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-run-angular.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-solution-structure.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/event-cloud-swagger-ui.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/swagger-ui-angular-api-v2.png
  doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/swagger-ui-angular-auth.png
Labels: enhancement, documentation, effort-sm

#6876 Update Aspect Oriented Programming using Interceptors document.
  doc/WebSite/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html
Labels: effort-sm

#6891 Normalize Key added with KeyPrefix in Redis Cache and TenantKeyEnabled
  src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs
  src/Abp.RedisCache.ProtoBuf/Runtime/Caching/Redis/AbpRedisCacheOptionsExtensions.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheKeyNormalizeArgs.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheKeyNormalizer.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheOptions.cs
  src/Abp.RedisCache/Runtime/Caching/Redis/IAbpRedisCacheKeyNormalizer.cs
  test/Abp.RedisCache.Tests/RedisCacheManager_Test.cs
  test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacement_Tests.cs
  test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCache_Test.cs
  test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataDtoControllerPermissionTests.cs
Labels: enhancement, effort-sm

#6895 Fix entity history problem
  src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
  test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
  test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Labels: in-progress
